"""
邮件发送模块
使用Gmail SMTP发送HTML邮件
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List, Dict, Any
from jinja2 import Environment, FileSystemLoader


class EmailSender:
    """邮件发送类"""

    def __init__(self, template_dir: str = 'templates'):
        """
        初始化邮件发送器

        Args:
            template_dir: 模板文件目录
        """
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
        self.sender_email = os.getenv('GMAIL_SENDER')
        self.sender_password = os.getenv('GMAIL_APP_PASSWORD')

        if not self.sender_email or not self.sender_password:
            raise ValueError("GMAIL_SENDER and GMAIL_APP_PASSWORD environment variables are required")

        # 设置Jinja2模板环境
        self.template_env = Environment(loader=FileSystemLoader(template_dir))

    def render_newsletter(self, categories: List[Dict[str, Any]]) -> str:
        """
        渲染新闻简报HTML

        Args:
            categories: 分类新闻数据

        Returns:
            渲染后的HTML字符串
        """
        template = self.template_env.get_template('newsletter.html')

        return template.render(
            date=datetime.now().strftime('%Y-%m-%d %A'),
            categories=categories
        )

    def send_newsletter(self, recipient: str, subject: str,
                       categories: List[Dict[str, Any]], sender_name: str = "AI News Bot") -> bool:
        """
        发送新闻简报邮件

        Args:
            recipient: 收件人邮箱
            subject: 邮件主题
            categories: 分类新闻数据
            sender_name: 发件人名称

        Returns:
            发送是否成功
        """
        try:
            # 渲染HTML内容
            html_content = self.render_newsletter(categories)

            # 创建邮件
            message = MIMEMultipart('alternative')
            message['Subject'] = subject
            message['From'] = f"{sender_name} <{self.sender_email}>"
            message['To'] = recipient

            # 创建纯文本版本（作为备用）
            text_content = self._create_text_version(categories)
            part1 = MIMEText(text_content, 'plain', 'utf-8')
            part2 = MIMEText(html_content, 'html', 'utf-8')

            message.attach(part1)
            message.attach(part2)

            # 发送邮件
            print(f"Connecting to SMTP server: {self.smtp_server}:{self.smtp_port}")
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                print(f"Logging in as: {self.sender_email}")
                server.login(self.sender_email, self.sender_password)
                print(f"Sending email to: {recipient}")
                server.send_message(message)

            print(f"Newsletter sent successfully to {recipient}")
            return True

        except Exception as e:
            print(f"Failed to send email: {e}")
            return False

    def _create_text_version(self, categories: List[Dict[str, Any]]) -> str:
        """
        创建邮件的纯文本版本

        Args:
            categories: 分类新闻数据

        Returns:
            纯文本内容
        """
        text_parts = [
            "AI WEEKLY NEWSLETTER - 人工智能周报",
            "=" * 60,
            f"Date: {datetime.now().strftime('%Y-%m-%d %A')}",
            "=" * 60,
            ""
        ]

        for category in categories:
            text_parts.append(f"\n## {category['category_name_en']}")
            text_parts.append(f"## {category['category_name_zh']}")
            text_parts.append("-" * 60)

            for i, item in enumerate(category['news_items'], 1):
                text_parts.append(f"\n{i}. {item['title']}")
                text_parts.append(f"   URL: {item['url']}")
                text_parts.append(f"   EN: {item['summary_en']}")
                text_parts.append(f"   中文: {item['summary_zh']}")
                if item.get('significance'):
                    text_parts.append(f"   💡 {item['significance']}")
                text_parts.append("")

        text_parts.append("\n" + "=" * 60)
        text_parts.append("Automatically generated by AI News Bot")
        text_parts.append("本简报由AI自动生成，每周一上午9:00发送")

        return "\n".join(text_parts)
